<a href="https://colab.research.google.com/github/KARPPAKAVALLI/ML_Projects/blob/main/NumPy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY ADVANTAGES:**


*   Better memory management.
*   Faster execution.
*   Highly efficient array operations.







---

NOTE: ARR MEANS NUMPY ARRAY (in this ipynb)


---



**IMPORT**

In [2]:
import numpy as np

**CREATION**

In [3]:
eg=[1,2,3,4,5]
print(eg)
print(type(eg))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
ar=np.array(eg)
print(ar)
print(type(ar))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**ARRAY WITH ALL ELEMS AS ZEROS**

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

**ARRAY WITH ALL ELEMS AS ONES**

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones(3,int)

array([1, 1, 1])

**ZERO BASED INDEXING**

In [9]:
demo=np.array([10,25,38])
demo[0]

10

**FINDING DATAYPE OF NUMPY ARRAY ELEMENTS**

In [10]:
demo.dtype

dtype('int64')

**CAN CONTAIN ONLY HOMOGENEOUS TYPE**


> i.e:- elements in a numpy arr should b of same type



In [11]:
demo[1]="abc"

ValueError: ignored

**MULTI-DIM NUMPY ARR**

In [13]:
a=np.zeros((2,3)) #NOTE: two paranthesis
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
b=np.zeros((4,2,5))
b
# 4 - arr of arr of arr
# 2 - each outer arr has two inner arr
# 5 - no.of cols / no. of elems in a single arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

**SHAPE FN - GIVES DIM OF AN ARR**

In [15]:
a.shape

(2, 3)

In [16]:
b.shape

(4, 2, 5)

**ARR SLICING**

In [17]:
eg=np.array([2,5,3,1,7])
eg[1:4] #index 1 to 3 (till n-1)

array([5, 3, 1])

**NEGATIVE INDICES**

In [18]:
eg[-1]

7